### ISSUE TITLE
Timeout in reconnect

### ISSUE THREAD

**Issue by bmario** [metricq/metricq-source-watchport#1]
```
Aug 06 11:21:42 energy metricq-source-watchport[29413]: sending RPC source.register, ex: metricq.management, rk: source.register, ci: metricq-rpc-py-source-elab-watchport-c6a242c4bbc045c6a50c629a93919c0e, args: {"function": "source.regist
Aug 06 11:22:42 energy metricq-source-watchport[29413]: error: Failed to connect WatchPortSource:  (TimeoutError)
Aug 06 11:22:42 energy metricq-source-watchport[29413]: Traceback (most recent call last):
Aug 06 11:22:42 energy metricq-source-watchport[29413]:   File "/home/zih/metricq-source-watchport/venv/lib/python3.6/site-packages/metricq/source.py", line 60, in connect
Aug 06 11:22:42 energy metricq-source-watchport[29413]:     response = await self.rpc("source.register")
Aug 06 11:22:42 energy metricq-source-watchport[29413]:   File "/home/zih/metricq-source-watchport/venv/lib/python3.6/site-packages/metricq/client.py", line 82, in rpc
Aug 06 11:22:42 energy metricq-source-watchport[29413]:     **kwargs,
Aug 06 11:22:42 energy metricq-source-watchport[29413]:   File "/home/zih/metricq-source-watchport/venv/lib/python3.6/site-packages/metricq/agent.py", line 380, in rpc
Aug 06 11:22:42 energy metricq-source-watchport[29413]:     return await asyncio.wait_for(request_future, timeout=timeout)
Aug 06 11:22:42 energy metricq-source-watchport[29413]:   File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
Aug 06 11:22:42 energy metricq-source-watchport[29413]:     raise futures.TimeoutError()
Aug 06 11:22:42 energy metricq-source-watchport[29413]: concurrent.futures._base.TimeoutError
Aug 06 11:22:42 energy metricq-source-watchport[29413]: The above exception was the direct cause of the following exception:
Aug 06 11:22:42 energy metricq-source-watchport[29413]: Traceback (most recent call last):
Aug 06 11:22:42 energy metricq-source-watchport[29413]:   File "/home/zih/metricq-source-watchport/venv/bin/metricq-source-watchport", line 10, in <module>
Aug 06 11:22:42 energy metricq-source-watchport[29413]:     sys.exit(source())
Aug 06 11:22:42 energy metricq-source-watchport[29413]:   File "/home/zih/metricq-source-watchport/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
Aug 06 11:22:42 energy metricq-source-watchport[29413]:     return self.main(*args, **kwargs)
Aug 06 11:22:42 energy metricq-source-watchport[29413]:   File "/home/zih/metricq-source-watchport/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
Aug 06 11:22:42 energy metricq-source-watchport[29413]:     rv = self.invoke(ctx)
Aug 06 11:22:42 energy metricq-source-watchport[29413]:   File "/home/zih/metricq-source-watchport/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
Aug 06 11:22:42 energy metricq-source-watchport[29413]:     return ctx.invoke(self.callback, **ctx.params)
Aug 06 11:22:42 energy metricq-source-watchport[29413]:   File "/home/zih/metricq-source-watchport/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
Aug 06 11:22:42 energy metricq-source-watchport[29413]:     return callback(*args, **kwargs)
Aug 06 11:22:42 energy metricq-source-watchport[29413]:   File "/home/zih/metricq-source-watchport/venv/lib/python3.6/site-packages/metricq_source_watchport/main.py", line 23, in source
Aug 06 11:22:42 energy metricq-source-watchport[29413]:     src.run()
Aug 06 11:22:42 energy metricq-source-watchport[29413]:   File "/home/zih/metricq-source-watchport/venv/lib/python3.6/site-packages/metricq/agent.py", line 282, in run
Aug 06 11:22:42 energy metricq-source-watchport[29413]:     self.event_loop.run_until_complete(wait_for_stop())
Aug 06 11:22:42 energy metricq-source-watchport[29413]:   File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
Aug 06 11:22:42 energy metricq-source-watchport[29413]:     return future.result()
Aug 06 11:22:42 energy metricq-source-watchport[29413]:   File "/home/zih/metricq-source-watchport/venv/lib/python3.6/site-packages/metricq/agent.py", line 273, in wait_for_stop
Aug 06 11:22:42 energy metricq-source-watchport[29413]:     raise ConnectFailedError("Failed to connect Agent") from exc
Aug 06 11:22:42 energy metricq-source-watchport[29413]: metricq.agent.ConnectFailedError: Failed to connect Agent

**Comment by bmario** [comment]
Fixed with updating metricq in d1a4c74
